title: GORTAZAR Legal Advisors
description: Navegando la Justicia con Sabiduría Ancestral
baseurl: "/gortazar-legaltech"
url: "https://gortazar-legaltech.github.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
languages: ["es", "pt", "it", "en"]
default_lang: "es"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
include:
  - .well-known