title: GORTAZAR Legal Advisors
description: Navegando la Justicia con Sabiduría Ancestral
baseurl: "/gortazar-legaltech/"  # porque se sirve desde /gortazar-legaltech directamente
url: "https://gortazar-legaltech.github.io/gortazar-legaltech"


theme: minima  # ✅ compatible
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Rutas personalizadas de tema local
layouts_dir: _layouts
includes_dir: _includes
sass:
  sass_dir: assets/css
  style: compressed


# Multiidioma - configuración por defecto
defaults:
  - scope:
      path: ""
    values:
      layout: default
      lang: es

# SEO básico
permalink: pretty
markdown: kramdown


title: GORTAZAR Legal Advisors
description: Navegando la Justicia con Sabiduría Ancestral
baseurl: "" 
url: "https://gortazar-legaltech.github.io/gortazar-legaltech"
theme: minima  # ✅ compatible
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

defaults:
  - scope:
      path: ""
    values:
      layout: default