theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-multiple-languages-plugin
defaults:
  - scope:
      path: ""
    values:
      layout: default
languages: [es, en, pt, it]
default_lang: es
