name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          cd docs
          bundle install

      - name: Install Jekyll and Bundler
        run: |
          gem install bundler jekyll
  
      - name: Build site from /docs
        run: |
          jekyll build --source docs --destination _site
  
      - name: Upload _site artifact
        uses: actions/upload-artifact@v3
        with:
          name: gortazar-site
          path: _site