name: Build and Upload Jekyll Site

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jekyll Build and Artifact Upload
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Jekyll and Bundler
        run: |
          gem install bundler jekyll

      - name: Build site from /docs
        run: |
          jekyll build --source docs --destination _site

      - name: Upload _site artifact
        uses: actions/upload-artifact@v3
        with:
          name: gortazar-site
          path: _site